[package]
name = "merkle-tree"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
hash = { path = "../hash" }
bigint = { git = "https://github.com/nervosnetwork/bigint" }

[dev-dependencies]
rand = "0.5"
